name: Corre Sonar Qube

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
     
  sonarcloud:
  
    runs-on: ubuntu-latest
  
    steps:
      
      - uses: actions/checkout@master
      
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v1.4


